services:
  postgres:
    image: postgres:latest
    container_name: identipay_postgres_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - identipay-network

  redis:
    image: redis:alpine
    container_name: identipay_redis_dev
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redisDB:/data

networks:
  identipay-network:
    driver: bridge

volumes:
  postgres:
  redisDB: