services:
  postgres:
    image: postgres:latest
    container_name: identipay_postgres_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - identipay-network

  identipay-api:
    container_name: identipay_api_prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DefaultConnection: ${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      didHostname: ${DIDHOSTNAME}
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - identipay-network

  redis:
    image: redis:alpine
    container_name: identipay_redis_dev
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redisDB:/data

networks:
  identipay-network:
    driver: bridge

volumes:
  postgres:
  redisDB: